### PR TITLE
libignition-transport9.0.0

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Fix #13

**Comment by Tobias-Fischer** [comment]
This fails on osx with `error: 'shared_mutex' is unavailable: introduced in macOS 10.12`. What is the best way to deal with this? Any clues @conda-forge/libignition-transport4?

**Comment by traversaro** [comment]
I guess this could be related to https://github.com/conda-forge/conda-forge.github.io/issues/891 . Note that the requirement was introduced in https://github.com/ignitionrobotics/ign-transport/pull/152 .

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro - let's see whether this does the job :)

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @conda-forge/libignition-transport4 :)

Please also close #13

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer ! For the branches for the older major releases, what is the best idea? We just create them if a new minor release of them come out and we need to generate a new version?

**Review by traversaro — APPROVED** [review]

**Pull request merged**
