### PR TITLE
manual protobuf migration v10 branch

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

For some reason the v10 branch didn't get the migration.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@traversaro - please have a look. Thanks!

**Review by traversaro — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
For some reason this didn't automerge - could you please merge @traversaro?

**Comment by traversaro** [comment]
> For some reason this didn't automerge - could you please merge @traversaro?

Done!

**Pull request merged**
