### PR TITLE
Remove too strict max_pin

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
See https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/12

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Just to understand, in this case we do not need to re-render the recipe because the max pin is not related to that?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I am not sure about the conda internals .. maybe @wolfv knows. In any case, it's always good practice to rerender :)

**Comment by Tobias-Fischer** [comment]
@conda-forge/libignition-transport4 this is ready to be merged :)

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer !

**Comment by wolfv** [comment]
@traversaro @Tobias-Fischer re-rendering is actually nothing conda does, but conda-forge (and specifically conda-smithy) do. It takes the recipe as input, and creates the CI pipelines (Azure pipelines, travis, etc.).

Usually, after some time, configurations change, build scripts change, Azure might change etc. So regenerating these configs with re-render ensures that the generated pipelines are up-to-date and work fine.

**Pull request merged**
